"""PR creation and management cycle.

Handles creating pull requests with comprehensive descriptions,
linking to issues, managing labels and reviewers.
"""

from typing import List, Optional, Dict, Any
from dataclasses import dataclass, field
from pathlib import Path
from datetime import datetime, timezone

from ..integrations.git_ops import GitOps
from ..integrations.github_client import GitHubClient
from ..analyzers.implementation_planner import ImplementationPlan
from ..integrations.test_runner import TestResult
from ..core.logger import AuditLogger, EventType
from ..core.state import WorkItem


@dataclass
class PRDetails:
    """Details for creating a pull request."""
    title: str
    body: str
    head_branch: str
    base_branch: str = "main"
    draft: bool = False
    labels: List[str] = field(default_factory=list)
    reviewers: List[str] = field(default_factory=list)
    issue_number: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "title": self.title,
            "body_length": len(self.body),
            "head_branch": self.head_branch,
            "base_branch": self.base_branch,
            "draft": self.draft,
            "labels": self.labels,
            "reviewers": self.reviewers,
            "issue_number": self.issue_number,
        }


@dataclass
class PRCreationResult:
    """Result of PR creation."""
    pr_number: int
    pr_url: str
    success: bool
    branch_pushed: bool
    pr_details: PRDetails
    error: Optional[str] = None
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "pr_number": self.pr_number,
            "pr_url": self.pr_url,
            "success": self.success,
            "branch_pushed": self.branch_pushed,
            "pr_details": self.pr_details.to_dict(),
            "error": self.error,
            "created_at": self.created_at.isoformat(),
        }


class PRCreator:
    """Creates pull requests with comprehensive descriptions.

    Responsibilities:
    - Generate PR titles and descriptions
    - Push feature branches to remote
    - Create PRs with proper formatting
    - Add labels and request reviews
    - Link PRs to issues
    - Handle errors gracefully
    """

    # Default PR labels by issue type
    DEFAULT_LABELS = {
        "feature": ["enhancement", "orchestrator"],
        "bug": ["bug", "orchestrator"],
        "refactor": ["refactor", "orchestrator"],
        "documentation": ["documentation", "orchestrator"],
    }

    # PR description template
    PR_TEMPLATE = """## Summary
{summary}

## Related Issue
Closes #{issue_number}

## Changes Made
{changes_made}

## Test Results
{test_results}

## Implementation Details
{implementation_details}

## Checklist
- [ ] Code follows project style guidelines
- [ ] Tests added/updated and passing
- [ ] Documentation updated if needed
- [ ] No breaking changes (or documented if unavoidable)

🤖 Generated by [Self-Reflexive Orchestrator](https://github.com/justin4957/self-reflexive-orchestrator)
"""

    def __init__(
        self,
        git_ops: GitOps,
        github_client: GitHubClient,
        logger: AuditLogger,
        default_base_branch: str = "main",
        default_reviewers: Optional[List[str]] = None,
    ):
        """Initialize PR creator.

        Args:
            git_ops: Git operations client
            github_client: GitHub API client
            logger: Audit logger
            default_base_branch: Default base branch for PRs
            default_reviewers: Default list of reviewers
        """
        self.git_ops = git_ops
        self.github_client = github_client
        self.logger = logger
        self.default_base_branch = default_base_branch
        self.default_reviewers = default_reviewers or []

        # Statistics
        self.total_prs_created = 0
        self.successful_prs = 0
        self.failed_prs = 0

    def create_pr_from_work_item(
        self,
        work_item: WorkItem,
        plan: ImplementationPlan,
        test_result: Optional[TestResult] = None,
        additional_context: Optional[str] = None,
    ) -> PRCreationResult:
        """Create PR from work item and implementation plan.

        Args:
            work_item: Work item with issue information
            plan: Implementation plan with changes
            test_result: Optional test results
            additional_context: Additional context for PR description

        Returns:
            PRCreationResult with PR information
        """
        issue_number = work_item.metadata.get("issue_number", int(work_item.item_id))

        self.logger.info(
            "Creating PR from work item",
            issue_number=issue_number,
            branch=plan.branch_name,
        )

        try:
            # Generate PR details
            pr_details = self._generate_pr_details(
                work_item=work_item,
                plan=plan,
                test_result=test_result,
                additional_context=additional_context,
            )

            # Push branch to remote
            branch_pushed = self._push_branch(pr_details.head_branch)

            if not branch_pushed:
                return PRCreationResult(
                    pr_number=0,
                    pr_url="",
                    success=False,
                    branch_pushed=False,
                    pr_details=pr_details,
                    error="Failed to push branch to remote",
                )

            # Create PR
            pr = self.github_client.create_pull_request(
                title=pr_details.title,
                body=pr_details.body,
                head=pr_details.head_branch,
                base=pr_details.base_branch,
                draft=pr_details.draft,
            )

            # Add labels if specified
            if pr_details.labels:
                self._add_labels(pr.number, pr_details.labels)

            # Request reviews if specified
            if pr_details.reviewers:
                self._request_reviews(pr.number, pr_details.reviewers)

            # Update statistics
            self.total_prs_created += 1
            self.successful_prs += 1

            self.logger.audit(
                EventType.PR_CREATED,
                f"Created PR #{pr.number} for issue #{issue_number}",
                resource_type="pr",
                resource_id=str(pr.number),
                metadata={
                    "issue_number": issue_number,
                    "branch": pr_details.head_branch,
                    "url": pr.html_url,
                },
            )

            return PRCreationResult(
                pr_number=pr.number,
                pr_url=pr.html_url,
                success=True,
                branch_pushed=True,
                pr_details=pr_details,
            )

        except Exception as e:
            self.failed_prs += 1
            self.total_prs_created += 1

            self.logger.error(
                "Failed to create PR",
                issue_number=issue_number if 'issue_number' in locals() else work_item.item_id,
                error=str(e),
                exc_info=True,
            )

            return PRCreationResult(
                pr_number=0,
                pr_url="",
                success=False,
                branch_pushed=branch_pushed if 'branch_pushed' in locals() else False,
                pr_details=pr_details if 'pr_details' in locals() else None,
                error=str(e),
            )

    def _generate_pr_details(
        self,
        work_item: WorkItem,
        plan: ImplementationPlan,
        test_result: Optional[TestResult],
        additional_context: Optional[str],
    ) -> PRDetails:
        """Generate PR details from work item and plan.

        Args:
            work_item: Work item with issue information
            plan: Implementation plan
            test_result: Optional test results
            additional_context: Additional context

        Returns:
            PRDetails for PR creation
        """
        # Generate title
        title = self._generate_pr_title(work_item, plan)

        # Generate body
        body = self._generate_pr_body(
            work_item=work_item,
            plan=plan,
            test_result=test_result,
            additional_context=additional_context,
        )

        # Determine labels
        labels = self._determine_labels(work_item)

        # Get reviewers
        reviewers = self.default_reviewers.copy()

        issue_number = work_item.metadata.get("issue_number", int(work_item.item_id))

        return PRDetails(
            title=title,
            body=body,
            head_branch=plan.branch_name,
            base_branch=self.default_base_branch,
            draft=False,
            labels=labels,
            reviewers=reviewers,
            issue_number=issue_number,
        )

    def _generate_pr_title(self, work_item: WorkItem, plan: ImplementationPlan) -> str:
        """Generate PR title.

        Args:
            work_item: Work item
            plan: Implementation plan

        Returns:
            PR title
        """
        # Use issue title directly, prefixed with phase/type if available
        issue_number = work_item.metadata.get("issue_number", int(work_item.item_id))
        title = work_item.metadata.get("title", f"Issue #{issue_number}")

        # Add phase prefix if present in title
        if not title.startswith("["):
            issue_type = work_item.metadata.get("issue_type", "")
            if issue_type:
                title = f"[{issue_type.title()}] {title}"

        return title

    def _generate_pr_body(
        self,
        work_item: WorkItem,
        plan: ImplementationPlan,
        test_result: Optional[TestResult],
        additional_context: Optional[str],
    ) -> str:
        """Generate comprehensive PR body.

        Args:
            work_item: Work item
            plan: Implementation plan
            test_result: Test results
            additional_context: Additional context

        Returns:
            Formatted PR body
        """
        # Summary
        summary = work_item.metadata.get("description", plan.pr_description)

        # Changes made
        changes_made = self._format_changes_made(plan)

        # Test results
        test_results = self._format_test_results(test_result)

        # Implementation details
        implementation_details = self._format_implementation_details(plan, additional_context)

        issue_number = work_item.metadata.get("issue_number", int(work_item.item_id))

        # Fill template
        body = self.PR_TEMPLATE.format(
            summary=summary,
            issue_number=issue_number,
            changes_made=changes_made,
            test_results=test_results,
            implementation_details=implementation_details,
        )

        return body

    def _format_changes_made(self, plan: ImplementationPlan) -> str:
        """Format changes made section.

        Args:
            plan: Implementation plan

        Returns:
            Formatted changes list
        """
        lines = []

        if plan.files_to_create:
            lines.append("### Files Created")
            for file in plan.files_to_create:
                lines.append(f"- `{file}`: New file")

        if plan.files_to_modify:
            lines.append("\n### Files Modified")
            for file in plan.files_to_modify:
                lines.append(f"- `{file}`: Updated")

        if plan.implementation_steps:
            lines.append("\n### Implementation Steps")
            for i, step in enumerate(plan.implementation_steps, 1):
                lines.append(f"{i}. {step.description}")

        return "\n".join(lines) if lines else "No files changed"

    def _format_test_results(self, test_result: Optional[TestResult]) -> str:
        """Format test results section.

        Args:
            test_result: Test results

        Returns:
            Formatted test results
        """
        if not test_result:
            return "⏭️ Tests not run yet"

        if test_result.success:
            return f"✅ All tests passing ({test_result.passed} passed, {test_result.failed} failed, {test_result.skipped} skipped)"

        failures_text = ""
        if test_result.failures:
            failures_text = "\n\n**Failing Tests:**\n"
            for failure in test_result.failures[:5]:  # Show first 5 failures
                failures_text += f"- `{failure.test_name}`: {failure.error_message}\n"
            if len(test_result.failures) > 5:
                failures_text += f"- ... and {len(test_result.failures) - 5} more"

        return f"❌ Tests failing ({test_result.passed} passed, {test_result.failed} failed){failures_text}"

    def _format_implementation_details(
        self,
        plan: ImplementationPlan,
        additional_context: Optional[str],
    ) -> str:
        """Format implementation details section.

        Args:
            plan: Implementation plan
            additional_context: Additional context

        Returns:
            Formatted implementation details
        """
        lines = []

        # Add plan description if available
        if plan.pr_description:
            lines.append(plan.pr_description)

        # Add test strategy
        if plan.test_strategy:
            lines.append(f"\n**Test Strategy:** {plan.test_strategy.coverage_requirements}")

        # Add complexity estimate
        if plan.estimated_total_complexity > 0:
            complexity_level = plan.confidence_level.value if plan.confidence_level else "unknown"
            lines.append(f"\n**Complexity:** {plan.estimated_total_complexity}/10 ({complexity_level} confidence)")

        # Add additional context
        if additional_context:
            lines.append(f"\n{additional_context}")

        return "\n".join(lines) if lines else "See implementation plan for details."

    def _determine_labels(self, work_item: WorkItem) -> List[str]:
        """Determine labels for PR based on work item.

        Args:
            work_item: Work item

        Returns:
            List of labels
        """
        labels = []

        # Get issue type from metadata
        issue_type = work_item.metadata.get("issue_type", "").lower()

        # Add default labels for issue type
        if issue_type in self.DEFAULT_LABELS:
            labels.extend(self.DEFAULT_LABELS[issue_type])
        else:
            labels.append("orchestrator")

        # Add phase label if present
        title = work_item.metadata.get("title", "")
        if "[Phase" in title:
            phase_match = title.split("]")[0].replace("[", "")
            labels.append(phase_match.lower().replace(" ", "-"))

        return list(set(labels))  # Remove duplicates

    def _push_branch(self, branch_name: str) -> bool:
        """Push branch to remote.

        Args:
            branch_name: Branch name to push

        Returns:
            True if successful, False otherwise
        """
        try:
            self.git_ops.push_branch(branch_name, set_upstream=True)
            self.logger.info("Branch pushed to remote", branch=branch_name)
            return True
        except Exception as e:
            self.logger.error(
                "Failed to push branch",
                branch=branch_name,
                error=str(e),
                exc_info=True,
            )
            return False

    def _add_labels(self, pr_number: int, labels: List[str]) -> None:
        """Add labels to PR.

        Args:
            pr_number: PR number
            labels: Labels to add
        """
        try:
            pr = self.github_client.get_pull_request(pr_number)
            pr.add_to_labels(*labels)
            self.logger.debug("Added labels to PR", pr_number=pr_number, labels=labels)
        except Exception as e:
            self.logger.warning(
                "Failed to add labels to PR",
                pr_number=pr_number,
                labels=labels,
                error=str(e),
            )

    def _request_reviews(self, pr_number: int, reviewers: List[str]) -> None:
        """Request reviews for PR.

        Args:
            pr_number: PR number
            reviewers: List of reviewer usernames
        """
        try:
            pr = self.github_client.get_pull_request(pr_number)
            pr.create_review_request(reviewers=reviewers)
            self.logger.debug("Requested reviews for PR", pr_number=pr_number, reviewers=reviewers)
        except Exception as e:
            self.logger.warning(
                "Failed to request reviews",
                pr_number=pr_number,
                reviewers=reviewers,
                error=str(e),
            )

    def get_statistics(self) -> Dict[str, Any]:
        """Get PR creation statistics.

        Returns:
            Dictionary with statistics
        """
        success_rate = (
            (self.successful_prs / self.total_prs_created * 100)
            if self.total_prs_created > 0
            else 0.0
        )

        return {
            "total_prs_created": self.total_prs_created,
            "successful_prs": self.successful_prs,
            "failed_prs": self.failed_prs,
            "success_rate": success_rate,
        }

    def reset_statistics(self):
        """Reset PR creation statistics."""
        self.total_prs_created = 0
        self.successful_prs = 0
        self.failed_prs = 0
